name: movieverse
description: Next-Gen Social Movie Recommendation App (starter scaffold)
version: 0.1.0
environment:
  sdk: ">=3.3.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.1.2
  http: ^1.2.1
  flutter_dotenv: ^5.1.0
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.3
  cloud_firestore: ^5.6.7
  firebase_analytics: ^11.4.5
  firebase_crashlytics: ^4.3.5
  firebase_messaging: ^15.2.5
  google_sign_in: ^6.0.0
  cached_network_image: ^3.0.0
  intl: ^0.19.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
flutter:
  uses-material-design: true
  assets:
    - .env